"""add product fields, system settings, maintenance log, chat conversation fields

Revision ID: 0ad52981b691
Revises: 3db3dea2fa0b
Create Date: 2026-08-16 18:16:11.759114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad52981b691'
down_revision: Union[str, Sequence[str], None] = '3db3dea2fa0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_logs_created_at'), 'maintenance_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_id'), 'maintenance_logs', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.add_column('ai_logs', sa.Column('conversation_id', sa.String(length=36), nullable=True))
    op.add_column('ai_logs', sa.Column('route', sa.String(length=20), nullable=True))
    op.add_column('ai_logs', sa.Column('intent', sa.String(length=50), nullable=True))
    op.create_index('idx_ai_logs_conversation_id', 'ai_logs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_logs_conversation_id'), 'ai_logs', ['conversation_id'], unique=False)
    op.add_column('products', sa.Column('subcategory', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('sku', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('production_level', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.alter_column('products', 'is_active', server_default=None)
    op.create_unique_constraint('uq_products_sku', 'products', ['sku'])

    # Seed default maintenance-mode settings so the app has a known state from day one.
    op.execute(
        "INSERT INTO system_settings (key, value, updated_at) VALUES "
        "('maintenance_mode', 'false', now()), "
        "('maintenance_message', 'SalesIQ is currently under maintenance. Please check back shortly.', now())"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_products_sku', 'products', type_='unique')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'production_level')
    op.drop_column('products', 'cost')
    op.drop_column('products', 'price')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'subcategory')
    op.drop_index(op.f('ix_ai_logs_conversation_id'), table_name='ai_logs')
    op.drop_index('idx_ai_logs_conversation_id', table_name='ai_logs')
    op.drop_column('ai_logs', 'intent')
    op.drop_column('ai_logs', 'route')
    op.drop_column('ai_logs', 'conversation_id')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_maintenance_logs_id'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_created_at'), table_name='maintenance_logs')
    op.drop_table('maintenance_logs')
    # ### end Alembic commands ###
