import React, { useState, useEffect } from 'react'
import { aiApi } from '../services/api'
import { AIInsightCard } from '../components/insights/AIInsightCard'
import { AnomalyCard } from '../components/insights/AnomalyCard'
import { RecommendationCard } from '../components/insights/RecommendationCard'
import { Sparkles, AlertTriangle, TrendingUp, RefreshCw, Info } from 'lucide-react'

const PERIODS = [
  { value: 'this_month', label: 'This Month' },
  { value: 'last_3_months', label: 'Last 3 Months' },
  { value: 'last_6_months', label: 'Last 6 Months' },
  { value: 'all_time', label: 'All Time' },
]

export const AIInsights = () => {
  const [period, setPeriod] = useState('this_month')
  const [insights, setInsights] = useState(null)
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState('')

  const fetchInsights = async (selectedPeriod = period) => {
    try {
      setGenerating(true)
      setError('')
      const res = await aiApi.getInsights({ period: selectedPeriod })
      if (res.data) setInsights(res.data)
    } catch (err) {
      setError(err.message || 'Failed to generate AI insights.')
    } finally {
      setGenerating(false)
      setLoading(false)
    }
  }

  useEffect(() => { fetchInsights('this_month') }, [])

  return (
    <div className="space-y-5 max-w-3xl">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold text-text tracking-tight">AI Insights</h1>
          <p className="text-xs text-text-dim mt-0.5">
            Intelligent pattern discovery, anomaly flags, and business growth recommendations
          </p>
        </div>

        <div className="flex items-center gap-2 flex-shrink-0 mt-0.5">
          <select
            value={period}
            onChange={e => { setPeriod(e.target.value); fetchInsights(e.target.value) }}
            className="bg-surface border border-border rounded px-2.5 py-1.5 text-xs font-semibold text-text focus:outline-none focus:border-secondary shadow-xs"
          >
            {PERIODS.map(p => <option key={p.value} value={p.value}>{p.label}</option>)}
          </select>
          <button
            onClick={() => fetchInsights(period)}
            disabled={generating}
            className="flex items-center gap-1.5 px-3.5 py-1.5 bg-primary hover:bg-primary-light disabled:opacity-50 text-white font-bold text-xs rounded shadow-xs transition-colors press-effect"
          >
            <Sparkles className={`w-3.5 h-3.5 text-accent-light ${generating ? 'animate-spin' : ''}`} />
            <span>{generating ? 'Synthesizing…' : 'Generate'}</span>
          </button>
        </div>
      </div>

      {/* Gemini disclaimer */}
      <div className="flex items-start gap-2 px-3.5 py-2.5 bg-primary-50 border border-primary/20 rounded-lg">
        <Info className="w-3.5 h-3.5 text-primary flex-shrink-0 mt-0.5" />
        <p className="text-xs text-text-muted">
          The AI summary is generated by <strong className="text-text">Gemini</strong> interpreting pre-computed analytics data.
          Numbers are fact-based; narrative interpretation may vary. Anomalies and recommendations use deterministic algorithms.
        </p>
      </div>

      {error && (
        <div className="p-3.5 bg-danger-bg border border-red-200 text-danger rounded-lg text-xs font-semibold">
          {error}
        </div>
      )}

      {loading ? (
        <div className="space-y-3 animate-pulse">
          <div className="h-32 skeleton rounded-lg" />
          <div className="h-20 skeleton rounded-lg" />
          <div className="h-20 skeleton rounded-lg" />
        </div>
      ) : insights ? (
        <div className="space-y-5">
          {/* Main AI Summary */}
          <AIInsightCard summaryText={insights.summary_text} generatedAt={insights.generated_at} />

          {/* Anomalies */}
          {insights.anomalies?.length > 0 && (
            <div className="space-y-2.5">
              <div className="flex items-center gap-2">
                <AlertTriangle className="w-3.5 h-3.5 text-warning" />
                <h3 className="text-xs font-bold text-text uppercase tracking-wider">
                  Detected Anomalies ({insights.anomalies.length})
                </h3>
              </div>
              <div className="space-y-2.5">
                {insights.anomalies.map(a => <AnomalyCard key={a.id} anomaly={a} />)}
              </div>
            </div>
          )}

          {/* Recommendations */}
          {insights.recommendations?.length > 0 && (
            <div className="space-y-2.5">
              <div className="flex items-center gap-2">
                <TrendingUp className="w-3.5 h-3.5 text-secondary" />
                <h3 className="text-xs font-bold text-text uppercase tracking-wider">
                  Recommendations ({insights.recommendations.length})
                </h3>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {insights.recommendations.map(r => <RecommendationCard key={r.id} recommendation={r} />)}
              </div>
            </div>
          )}
        </div>
      ) : null}
    </div>
  )
}
